services:
  dynamodb-local:
    image: "amazon/dynamodb-local:latest"
    container_name: dynamodb-local
    healthcheck:
      test: ["CMD-SHELL", "curl -s -o /dev/null http://localhost:8000 || exit 1"]
      interval: 2s
      timeout: 10s
      retries: 5
    ports:
      - "8000:8000"
