Feature: Invoke-APIGateway-HappyPath.feature

    Scenario Outline: Happy Path - Get Request to /ais/userId - Returns Expected Data for <aisEventType>
        Given I send an <aisEventType> intervention message to the TxMA ingress SQS queue
        When I invoke the API to retrieve the intervention status of the user's account. With history <historyValue>
        Then I expect the intervention to be <interventionType>, with the following state settings <blockedState>, <suspendedState>, <resetPassword> and <reproveIdentity>
        Examples:
            | aisEventType              | historyValue | interventionType                                   | blockedState | suspendedState | resetPassword | reproveIdentity |
            | pswResetRequired          | false        | AIS_FORCED_USER_PASSWORD_RESET                     | false        | true           | true          | false           |
            | suspendNoAction           | false        | AIS_ACCOUNT_SUSPENDED                              | false        | true           | false         | false           |
            | block                     | false        | AIS_ACCOUNT_BLOCKED                                | true         | false          | false         | false           |
            | idResetRequired           | false        | AIS_FORCED_USER_IDENTITY_VERIFY                    | false        | true           | false         | true            |
            | pswAndIdResetRequired     | false        | AIS_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_VERIFY | false        | true           | true          | true            |
            | unblock                   | false        | AIS_NO_INTERVENTION                                | false        | false          | false         | false           |
            | userActionIdResetSuccess  | false        | AIS_NO_INTERVENTION                                | false        | false          | false         | false           |
            | userActionPswResetSuccess | false        | AIS_NO_INTERVENTION                                | false        | false          | false         | false           |
            | unSuspendAction           | false        | AIS_NO_INTERVENTION                                | false        | false          | false         | false           |

    Scenario Outline: Happy Path - <originalAisEventType> account - Get Request to /ais/userId - Returns Expected Data for <aisEventType>
        Given I send an <aisEventType> intervention message to the TxMA ingress SQS queue for a Account in <originalAisEventType> state
        When I invoke the API to retrieve the intervention status of the user's account. With history <historyValue>
        Then I expect the intervention to be <interventionType>, with the following state settings <blockedState>, <suspendedState>, <resetPassword>, <reproveIdentity>, <codeHistory> and <interventionHistory>
        Examples:
            | originalAisEventType  | aisEventType              | historyValue | interventionType                                   | blockedState | suspendedState | resetPassword | reproveIdentity | codeHistory | interventionHistory                                          |
            #passsword reset account status to new intervention type
            | pswResetRequired      | pswResetRequired          | true         | AIS_FORCED_USER_PASSWORD_RESET                     | false        | true           | true          | false           | 04          | FRAUD_FORCED_USER_PASSWORD_RESET                             |
            | pswResetRequired      | suspendNoAction           | true         | AIS_ACCOUNT_SUSPENDED                              | false        | true           | false         | false           | 01          | FRAUD_SUSPEND_ACCOUNT                                        |
            | pswResetRequired      | block                     | true         | AIS_ACCOUNT_BLOCKED                                | true         | false          | false         | false           | 03          | FRAUD_BLOCK_ACCOUNT                                          |
            | pswResetRequired      | idResetRequired           | true         | AIS_FORCED_USER_IDENTITY_VERIFY                    | false        | true           | false         | true            | 05          | FRAUD_FORCED_USER_IDENTITY_REVERIFICATION                    |
            | pswResetRequired      | pswAndIdResetRequired     | true         | AIS_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_VERIFY | false        | true           | true          | true            | 06          | FRAUD_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_REVERIFICATION |
            | pswResetRequired      | unblock                   | true         | AIS_FORCED_USER_PASSWORD_RESET                     | false        | true           | true          | false           | 04          | FRAUD_FORCED_USER_PASSWORD_RESET                             |
            | pswResetRequired      | userActionIdResetSuccess  | true         | AIS_FORCED_USER_PASSWORD_RESET                     | false        | true           | true          | false           | 04          | FRAUD_FORCED_USER_PASSWORD_RESET                             |
            | pswResetRequired      | userActionPswResetSuccess | true         | AIS_FORCED_USER_PASSWORD_RESET                     | false        | true           | true          | false           | 04          | FRAUD_FORCED_USER_PASSWORD_RESET                             |
            | pswResetRequired      | unSuspendAction           | true         | AIS_FORCED_USER_PASSWORD_RESET                     | false        | true           | true          | false           | 04          | FRAUD_FORCED_USER_PASSWORD_RESET                             |
            #suspend no action account status to new intervention type
            | suspendNoAction       | pswResetRequired          | true         | AIS_FORCED_USER_PASSWORD_RESET                     | false        | true           | true          | false           | 04          | FRAUD_FORCED_USER_PASSWORD_RESET                             |
            | suspendNoAction       | suspendNoAction           | true         | AIS_ACCOUNT_SUSPENDED                              | false        | true           | false         | false           | 01          | FRAUD_SUSPEND_ACCOUNT                                        |
            | suspendNoAction       | block                     | true         | AIS_ACCOUNT_BLOCKED                                | true         | false          | false         | false           | 03          | FRAUD_BLOCK_ACCOUNT                                          |
            | suspendNoAction       | idResetRequired           | true         | AIS_FORCED_USER_IDENTITY_VERIFY                    | false        | true           | false         | true            | 05          | FRAUD_FORCED_USER_IDENTITY_REVERIFICATION                    |
            | suspendNoAction       | pswAndIdResetRequired     | true         | AIS_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_VERIFY | false        | true           | true          | true            | 06          | FRAUD_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_REVERIFICATION |
            | suspendNoAction       | unblock                   | true         | AIS_ACCOUNT_SUSPENDED                              | false        | true           | false         | false           | 01          | FRAUD_SUSPEND_ACCOUNT                                        |
            | suspendNoAction       | userActionIdResetSuccess  | true         | AIS_ACCOUNT_SUSPENDED                              | false        | true           | false         | false           | 01          | FRAUD_SUSPEND_ACCOUNT                                        |
            | suspendNoAction       | userActionPswResetSuccess | true         | AIS_ACCOUNT_SUSPENDED                              | false        | true           | false         | false           | 01          | FRAUD_SUSPEND_ACCOUNT                                        |
            | suspendNoAction       | unSuspendAction           | true         | AIS_ACCOUNT_SUSPENDED                              | false        | true           | false         | false           | 01          | FRAUD_SUSPEND_ACCOUNT                                        |
            # blocked account status to new intervention type
            | block                 | pswResetRequired          | true         | AIS_FORCED_USER_PASSWORD_RESET                     | false        | true           | true          | false           | 04          | FRAUD_FORCED_USER_PASSWORD_RESET                             |
            | block                 | suspendNoAction           | true         | AIS_ACCOUNT_SUSPENDED                              | false        | true           | false         | false           | 01          | FRAUD_SUSPEND_ACCOUNT                                        |
            | block                 | block                     | true         | AIS_ACCOUNT_BLOCKED                                | true         | false          | false         | false           | 03          | FRAUD_BLOCK_ACCOUNT                                          |
            | block                 | idResetRequired           | true         | AIS_FORCED_USER_IDENTITY_VERIFY                    | false        | true           | false         | true            | 05          | FRAUD_FORCED_USER_IDENTITY_REVERIFICATION                    |
            | block                 | pswAndIdResetRequired     | true         | AIS_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_VERIFY | false        | true           | true          | true            | 06          | FRAUD_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_REVERIFICATION |
            | block                 | unblock                   | true         | AIS_ACCOUNT_BLOCKED                                | true         | false          | false         | false           | 03          | FRAUD_BLOCK_ACCOUNT                                          |
            | block                 | userActionIdResetSuccess  | true         | AIS_ACCOUNT_BLOCKED                                | true         | false          | false         | false           | 03          | FRAUD_BLOCK_ACCOUNT                                          |
            | block                 | userActionPswResetSuccess | true         | AIS_ACCOUNT_BLOCKED                                | true         | false          | false         | false           | 03          | FRAUD_BLOCK_ACCOUNT                                          |
            | block                 | unSuspendAction           | true         | AIS_ACCOUNT_BLOCKED                                | true         | false          | false         | false           | 03          | FRAUD_BLOCK_ACCOUNT                                          |
            # Id reset account status to new intervention type
            | idResetRequired       | pswResetRequired          | true         | AIS_FORCED_USER_PASSWORD_RESET                     | false        | true           | true          | false           | 04          | FRAUD_FORCED_USER_PASSWORD_RESET                             |
            | idResetRequired       | suspendNoAction           | true         | AIS_ACCOUNT_SUSPENDED                              | false        | true           | false         | false           | 01          | FRAUD_SUSPEND_ACCOUNT                                        |
            | idResetRequired       | block                     | true         | AIS_ACCOUNT_BLOCKED                                | true         | false          | false         | false           | 03          | FRAUD_BLOCK_ACCOUNT                                          |
            | idResetRequired       | idResetRequired           | true         | AIS_FORCED_USER_IDENTITY_VERIFY                    | false        | true           | false         | true            | 05          | FRAUD_FORCED_USER_IDENTITY_REVERIFICATION                    |
            | idResetRequired       | pswAndIdResetRequired     | true         | AIS_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_VERIFY | false        | true           | true          | true            | 06          | FRAUD_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_REVERIFICATION |
            | idResetRequired       | unblock                   | true         | AIS_FORCED_USER_IDENTITY_VERIFY                    | false        | true           | false         | true            | 05          | FRAUD_FORCED_USER_IDENTITY_REVERIFICATION                    |
            | idResetRequired       | userActionIdResetSuccess  | true         | AIS_FORCED_USER_IDENTITY_VERIFY                    | false        | true           | false         | true            | 05          | FRAUD_FORCED_USER_IDENTITY_REVERIFICATION                    |
            | idResetRequired       | userActionPswResetSuccess | true         | AIS_FORCED_USER_IDENTITY_VERIFY                    | false        | true           | false         | true            | 05          | FRAUD_FORCED_USER_IDENTITY_REVERIFICATION                    |
            | idResetRequired       | unSuspendAction           | true         | AIS_FORCED_USER_IDENTITY_VERIFY                    | false        | true           | false         | true            | 05          | FRAUD_FORCED_USER_IDENTITY_REVERIFICATION                    |
            # password reset required account status to new intervention type
            | pswAndIdResetRequired | pswResetRequired          | true         | AIS_FORCED_USER_PASSWORD_RESET                     | false        | true           | true          | false           | 04          | FRAUD_FORCED_USER_PASSWORD_RESET                             |
            | pswAndIdResetRequired | suspendNoAction           | true         | AIS_ACCOUNT_SUSPENDED                              | false        | true           | false         | false           | 01          | FRAUD_SUSPEND_ACCOUNT                                        |
            | pswAndIdResetRequired | block                     | true         | AIS_ACCOUNT_BLOCKED                                | true         | false          | false         | false           | 03          | FRAUD_BLOCK_ACCOUNT                                          |
            | pswAndIdResetRequired | idResetRequired           | true         | AIS_FORCED_USER_IDENTITY_VERIFY                    | false        | true           | false         | true            | 05          | FRAUD_FORCED_USER_IDENTITY_REVERIFICATION                    |
            | pswAndIdResetRequired | pswAndIdResetRequired     | true         | AIS_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_VERIFY | false        | true           | true          | true            | 06          | FRAUD_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_REVERIFICATION |
            | pswAndIdResetRequired | unblock                   | true         | AIS_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_VERIFY | false        | true           | true          | true            | 06          | FRAUD_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_REVERIFICATION |
            | pswAndIdResetRequired | userActionIdResetSuccess  | true         | AIS_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_VERIFY | false        | true           | true          | true            | 06          | FRAUD_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_REVERIFICATION |
            | pswAndIdResetRequired | userActionPswResetSuccess | true         | AIS_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_VERIFY | false        | true           | true          | true            | 06          | FRAUD_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_REVERIFICATION |
            | pswAndIdResetRequired | unSuspendAction           | true         | AIS_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_VERIFY | false        | true           | true          | true            | 06          | FRAUD_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_REVERIFICATION |
            # unblock account status to new intervention type
            | unblock               | pswResetRequired          | true         | AIS_FORCED_USER_PASSWORD_RESET                     | false        | true           | true          | false           | 04          | FRAUD_FORCED_USER_PASSWORD_RESET                             |
            | unblock               | suspendNoAction           | true         | AIS_ACCOUNT_SUSPENDED                              | false        | true           | false         | false           | 01          | FRAUD_SUSPEND_ACCOUNT                                        |
            | unblock               | block                     | true         | AIS_ACCOUNT_BLOCKED                                | true         | false          | false         | false           | 03          | FRAUD_BLOCK_ACCOUNT                                          |
            | unblock               | idResetRequired           | true         | AIS_FORCED_USER_IDENTITY_VERIFY                    | false        | true           | false         | true            | 05          | FRAUD_FORCED_USER_IDENTITY_REVERIFICATION                    |
            | unblock               | pswAndIdResetRequired     | true         | AIS_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_VERIFY | false        | true           | true          | true            | 06          | FRAUD_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_REVERIFICATION |
            | unblock               | unblock                   | true         | AIS_NO_INTERVENTION                                | false        | false          | false         | false           |             |                                                              |
            | unblock               | userActionIdResetSuccess  | true         | AIS_NO_INTERVENTION                                | false        | false          | false         | false           |             |                                                              |
            | unblock               | userActionPswResetSuccess | true         | AIS_NO_INTERVENTION                                | false        | false          | false         | false           |             |                                                              |
            | unblock               | unSuspendAction           | true         | AIS_NO_INTERVENTION                                | false        | false          | false         | false           |             |                                                              |
            #unsuspended account status to new intervention type
            | unSuspendAction | pswResetRequired          | true | AIS_FORCED_USER_PASSWORD_RESET                     | false | true  | true  | false | 04 | FRAUD_FORCED_USER_PASSWORD_RESET                             |
            | unSuspendAction | suspendNoAction           | true | AIS_ACCOUNT_SUSPENDED                              | false | true  | false | false | 01 | FRAUD_SUSPEND_ACCOUNT                                        |
            | unSuspendAction | block                     | true | AIS_ACCOUNT_BLOCKED                                | true  | false | false | false | 03 | FRAUD_BLOCK_ACCOUNT                                          |
            | unSuspendAction | idResetRequired           | true | AIS_FORCED_USER_IDENTITY_VERIFY                    | false | true  | false | true  | 05 | FRAUD_FORCED_USER_IDENTITY_REVERIFICATION                    |
            | unSuspendAction | pswAndIdResetRequired     | true | AIS_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_VERIFY | false | true  | true  | true  | 06 | FRAUD_FORCED_USER_PASSWORD_RESET_AND_IDENTITY_REVERIFICATION |
            | unSuspendAction | unblock                   | true | AIS_NO_INTERVENTION                                | false | false | false | false |    |                                                              |
            | unSuspendAction | userActionIdResetSuccess  | true | AIS_NO_INTERVENTION                                | false | false | false | false |    |                                                              |
            | unSuspendAction | userActionPswResetSuccess | true | AIS_NO_INTERVENTION                                | false | false | false | false |    |                                                              |
            | unSuspendAction | unSuspendAction           | true | AIS_NO_INTERVENTION                                | false | false | false | false |    |                                                              |


    Scenario Outline: Happy Path - Field Validation - Get Request to /ais/userId - Returns Expected Data for <aisEventType> with specific field validation
        Given I send a invalid request to sqs queue with no userId and <aisEventType>, <testUserId> data
        When I invoke apiGateway to retreive the status of the invalid userId with <historyValue>
        Then I should receive the appropriate <interventionType> for the ais endpoint
        Examples:
            | aisEventType    | historyValue | interventionType    | testUserId |
            | suspendNoAction | false        | AIS_NO_INTERVENTION |            |
