export const LOGS_PREFIX_SENSITIVE_INFO = 'Sensitive info -';
export const LOGS_PREFIX_INVALID_CONFIG = 'Invalid configuration -';

export enum MetricNames {
  DB_DELETE_ERROR_NO_RESPONSE = 'DB_DELETE_ERROR_NO_RESPONSE',
  DB_QUERY_HAS_LEK = 'DB_QUERY_HAS_LEK',
  DB_QUERY_ERROR_NO_RESPONSE = 'DB_QUERY_ERROR_NO_RESPONSE',
  INTERVENTION_EVENT_INVALID = 'INTERVENTION_EVENT_INVALID',
  INTERVENTION_INVALID = 'INTERVENTION_INVALID',
}

export enum AISInterventionTypes {
  AIS_NO_INTERVENTION = 'AIS_NO_INTERVENTION',
  AIS_ACCOUNT_SUSPENDED = 'AIS_ACCOUNT_SUSPENDED',
  AIS_ACCOUNT_UNSUSPENDED = 'AIS_ACCOUNT_UNSUSPENDED',
  AIS_ACCOUNT_BLOCKED = 'AIS_ACCOUNT_BLOCKED',
  AIS_ACCOUNT_UNBLOCKED = 'AIS_ACCOUNT_UNBLOCKED',
  AIS_USER_PASSWORD_RESET = 'AIS_USER_PASSWORD_RESET', //pragma: allowlist secret
  AIS_USER_IDENTITY_VERIFIED = 'AIS_USER_IDENTITY_VERIFIED',
  AIS_USER_PASSWORD_RESET_AND_IDENTITY_VERIFIED = 'AIS_USER_PASSWORD_RESET_AND_IDENTITY_VERIFIED', //pragma: allowlist secret
}
