name: 'Ensure SHA Pinned Actions'
permissions:
  contents: read

on:
  push:
    paths:
      - '.github/workflows/*'

jobs:
  harden_security:
    name: Harden Security
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6.0.2
      - name: Ensure SHA Pinned Actions
        uses: zgosalvez/github-actions-ensure-sha-pinned-actions@70c4af2ed5282c51ba40566d026d6647852ffa3e # pin@v5.0.1
