---
name: 'Validate & Publish Core SAM Template'

on:
  push:
    branches:
      - main
    paths:
      - 'src/infra/core/**'
      - '.github/workflows/merge-core-to-main.yaml'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validate_deployment:
    name: Deployment Template Checks
    uses: ./.github/workflows/validate-core-sam-template.yaml
    with:
      gitRef: ${{ inputs.gitRef }}
    secrets:
      githubActionsRoleARN: ${{ secrets.CORE_GH_ACTIONS_ROLE_ARN }}

  publish_artifacts:
    name: 'Publish Image & Template'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # pin@v6.0.2
        with:
          ref: ${{ inputs.gitRef }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@8df5847569e6427dd6c4fb1cf565c83acfa8afa7 # pin@6.0.0
        with:
          role-to-assume: ${{ secrets.CORE_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: 'Deploy SAM app'
        uses: govuk-one-login/devplatform-upload-action@b7bc01ed6e0b61d54f42e7f3d12dd3fdbb0f172a # pin@v3.13.0
        with:
          artifact-bucket-name: ${{ secrets.CORE_ARTIFACT_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.SIGNING_PROFILE_NAME }}
          working-directory: ./src/infra/core/
          template-file: template.yaml

      - name: 'Delegated Deployment via AWS CodeDeploy'
        run: echo "Deployment has been delegated to AWS CodeDeploy"
