name: Run Pact Tests For API Provider

env:
  PACT_BROKER_USER: ${{ secrets.PACT_BROKER_USER }}
  PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
  PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
  PACT_BROKER_SOURCE_SECRET: ${{ secrets.PACT_BROKER_SOURCE_SECRET }}
  GIT_BRANCH: ${{ github.head_ref || github.ref_name }}
  PROVIDER_APP_VERSION: ${{ github.sha }}
  PUBLISH_RESULT: false
  PACT_BROKER_CAN_I_DEPLOY_DRY_RUN: true

on:
  push:
    paths:
      - src/**
      - package.json
      - yarn.lock
      - tsconfig.json
      - .node-version
      - .github/workflows/pact-test-api-provider.yaml
    branches:
      - main
  pull_request:
    paths:
      - src/**
      - package.json
      - yarn.lock
      - tsconfig.json
      - .node-version
      - .github/workflows/pact-test-api-provider.yaml
    branches:
      - main
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  workflow_dispatch:
    inputs:
      gitRef:
        description: "Input branch name, commit SHA, or tag"
        required: true
        type: string
        default: main

permissions:
  contents: read

jobs:
  contract-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # pin@v3
        with:
          ref: ${{ inputs.gitRef || github.ref }}

      - name: Setup NodeJS
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # pin@v3
        with:
          node-version-file: '.node-version'

      - name: Run yarn install
        run: yarn install --frozen-lockfile

      - name: Set up pact publishing
        if: github.ref_name == 'main'
        run: echo "PUBLISH_RESULT=true" >> "$GITHUB_ENV"

      - name: Run pact tests for provider API
        run: |
          yarn connect:pact:broker
          yarn test:pact:provider

      - name: Run can-i-deploy check for AIS provider api
        if: github.ref_name == 'main'
        run: yarn pact:can-i-deploy
